engines:
  # ... CONFIG CONTENT ...
  phpmd:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Naming/LongVariable:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
      ExcessivePublicCount:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
# ... CONFIG CONTENT ...
